### ISSUE TITLE
warnings on newer perl releases

### ISSUE THREAD

**Issue by swsch** [choptastic/fed#2]
After copying fed.pl to my local bin directory, I see these warnings:

````
$ fed fed
Smartmatch is experimental at /home/stefan/.local/bin/fed line 391.
Possible precedence issue with control flow operator at /home/stefan/.local/bin/fed line 408.
````

Since my perl-foo is not strong, I did some searching and came up with the following ad-hoc fixes that work for me (TM) on my perl v5.20.2:

````
diff --git a/fed.pl b/fed.pl
index 6866831..f64292d 100755
--- a/fed.pl
+++ b/fed.pl
@@ -3,6 +3,7 @@
 use strict;
 use warnings;
 use Cwd;
+use experimental 'smartmatch';
 
 &main(@ARGV);
 
@@ -405,5 +406,5 @@ sub get_until_valid_range {
 
 sub is_integer {
        my ($val) = @_;
-       return !ref($val) and $val == int($val); ## tests whether is numerically equal to itself.
+       return (!ref($val) and $val == int($val)); ## tests whether is numerically equal to itself.
 }
````

**Comment by choptastic** [comment]
Thanks a bunch!

Get this merged in when I get back to my computer.

Cheers,

-Jesse

**Comment by choptastic** [comment]
Thanks, I removed the reliance on the smartmatch operator given its experimental nature (of which I was unaware when I built fed).  Thanks a lot!

**Comment by swsch** [comment]
I read that there was a time (before 5.18) when smartmatch was not experimental :-)
